const languages = {
    "bg": "Български",
    "cs": "Čeština",
    "da": "Dansk",
    "de": "Deutsch",
    "el": "Ελληνικά",
    "en": "English",
    "es": "Español",
    "et": "Eesti",
    "fi": "Suomi",
    "fil": "Filipino",
    "fr": "Français",
    "ga": "Gaeilge",
    "hr": "Hrvatski",
    "is": "Íslenska",
    "it": "Italiano",
    "ja": "日本語",
    "ko": "한국어",
    "lt": "Lietuvių",
    "lo": "LOLCAT",
    "mk": "Македонски",
    "nl": "Nederlands",
    "pl": "Polski",
    "ro": "Română",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "sv": "Svenska",
    "uk": "Українська",
    "zh": "中文"
}

export default languages
